[build-system]
requires = ["setuptools>=61.0", "tinytag>=1.8.1", "typed-argument-parser>=1.7.2"]
build-backend = "setuptools.build_meta"

[project]
name = "musort"
version = "0.0.1"
authors = [
  { name="ernieIzde8ski" },
]
description = "A music-sorting package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ernieIzde8ski/mus_sort/tree/pypi-module"
"Bug Tracker" = "https://github.com/ernieIzde8ski/mus_sort/issues"
