"""
This type stub file was generated by pyright.
"""

__all__ = ["__version__", "Flac", "ID3", "Ogg", "TinyTag", "TinyTagException", "Wave"]

from typing_extensions import LiteralString

from .tinytag import ID3, Flac, Ogg, TinyTag, TinyTagException, Wave

__version__: LiteralString = ...

if __name__ == "__main__":
    ...
